version: "3.9"
services:
  jlab:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      TZ: Asia/Tokyo
    tty: true
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=''
      --notebook-dir=/workspace
    expose:
      - "8888"
    ports:
      - "8888:8888"
    volumes:
      - ./:/root/.jupyter
      - ./workspace:/workspace
    working_dir: /workspace

# GPUを使う場合の設定
#    environment:
#      - "NVIDIA_VISIBLE_DEVICES=all"
#      - "NVIDIA_DRIVER_CAPABILITIES=all"
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - capabilities:
#              - gpu
